### ISSUE TITLE
Openvino : TypeError: __cinit__() got an unexpected keyword argument 'weights'

### ISSUE THREAD

**Issue by jangsiye** [animikhaich/Real-Time-Face-Anonymizer#6]
Hello, I'm inquiring because there was an error that I couldn't solve while testing your masking tool. The error is related to OPENVINO.  

I read OPENVINO's document, but I couldn't understand why the typeerror error occurred.  

```
{
    "weights_folder": "weights",
    "processing_device": "CPU",
    "detection_confidence": 0.75,
    "blur_strength": 99,
    "display_live": true,
    "write_video": true,
    "stacked_video": false,
    "input": "video/220107_524-Unjeong_2_1.avi",
    "output": "output/220107_524-Unjeong_2_1.avi"
}
2022-04-12 17:58:26,681: INFO: Initializing plugin for CPU device...
2022-04-12 17:58:26,686: INFO: Reading IR...
Traceback (most recent call last):
  File "D:\labeling_tools\Real-Time-Face-Anonymizer\main.py", line 19, in <module>
    face_detector = OpenVINOFaceDetector(config=config)
  File "D:\labeling_tools\Real-Time-Face-Anonymizer\face_detection\detector.py", line 23, in __init__
    self.n, self.c, self.h, self.w = self.infer_network.load_model(
  File "D:\labeling_tools\Real-Time-Face-Anonymizer\face_detection\intel_inference.py", line 83, in load_model
    self.net = IENetwork(model=model_xml, weights=model_bin)
  File "ie_api.pyx", line 1598, in openvino.inference_engine.ie_api.IENetwork.__cinit__
TypeError: __cinit__() got an unexpected keyword argument 'weights'
```

The same error occurred when I changed processing_device to GPU.

This is my spac :
- window10
- python3.9
- Intel OpenVINO 2020.3 LTS
- CPU : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   3.60 GHz  
- GPU : Titan XP * 1 

Thanks!

**Comment by Etty-Cohen** [comment]
Hi @jangsiye ,
did you solved it? I have that error too

**Comment by jangsiye** [comment]
@Etty-Cohen No, it has not been resolved. I am using another Face detector. T.T

**Comment by Etty-Cohen** [comment]
@jangsiye Thanks!

**Comment by HelenTsvetkova** [comment]
same .. :(
```py
from openvino.inference_engine import IECore
from openvino.inference_engine import IENetwork

model = "models/blazeface"
# Loading the Inference Engine API
ie = IECore()
# Loading IR files
net = IENetwork(model=model + ".xml", weights=model + ".bin")
# Loading the network to the inference engine
exec_net = ie.load_network(network=net, device_name="CPU")
```
Error
```py
File "/home/helen/class/opencv-blog/PyTorch_ONNX_OpenVINO/inference_openvino.py", line 43, in <module>
    net = IENetwork(model=model + ".xml", weights=model + ".bin")
  File "ie_api.pyx", line 1598, in openvino.inference_engine.ie_api.IENetwork.__cinit__
TypeError: __cinit__() got an unexpected keyword argument 'weights'
```

**Comment by shivohtouchlab** [comment]
Same error in here too.

**Comment by animikhaich** [comment]
Hi @jangsiye @shivohtouchlab @HelenTsvetkova @Etty-Cohen 

Thanks for reporting the issue. Sorry for the delay. I've been moving countries and was went back to school for my graduate degree. Got a bit busy, didn't get time to look into this. 

Would any of you be able to try out this branch for the fix: https://github.com/animikhaich/OpenVINO-Real-Time-Face-Anonymizer/tree/copilot/fix-openvino-typeerror

This is a PR raised by Copilot. Unfortunately, I no longer use an Intel CPU and can't test OpenVINO. Let me know if  you'd like to try out the fix. Would appreciate it!

**Comment by webbrain-one** [comment]
Hi! Thanks for the detailed report.

I've opened a pull request to fix this `TypeError` regarding the `weights` argument: https://github.com/animikhaich/OpenVINO-Real-Time-Face-Anonymizer/pull/9

This updates the initialization code to be compatible with the OpenVINO API. Let me know if this resolves the issue for you!
